import {
  Award,
  BadgeCheck,
  BookOpen,
  Brain,
  Building2,
  Bus,
  Calculator,
  CalendarDays,
  Clock,
  Dumbbell,
  FlaskConical,
  Globe,
  GraduationCap,
  HandHeart,
  Handshake,
  Heart,
  HeartHandshake,
  Landmark,
  Languages,
  Laptop,
  Leaf,
  Library,
  Lightbulb,
  MapPin,
  Medal,
  Megaphone,
  Microscope,
  MonitorSmartphone,
  Music,
  Palette,
  PenTool,
  Rocket,
  School,
  ShieldCheck,
  Smile,
  Sparkles,
  Star,
  Target,
  Theater,
  Trophy,
  Users,
  Utensils,
  Volleyball,
  type LucideIcon,
} from "lucide-react";

/**
 * Icons an admin can pick for highlights and statistics. A fixed list keeps the
 * bundle small and the admin picker simple.
 */
export const ICONS: Record<string, LucideIcon> = {
  award: Award,
  "badge-check": BadgeCheck,
  "book-open": BookOpen,
  brain: Brain,
  building: Building2,
  bus: Bus,
  calculator: Calculator,
  calendar: CalendarDays,
  clock: Clock,
  dumbbell: Dumbbell,
  flask: FlaskConical,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "hand-heart": HandHeart,
  handshake: Handshake,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  landmark: Landmark,
  languages: Languages,
  laptop: Laptop,
  leaf: Leaf,
  library: Library,
  lightbulb: Lightbulb,
  "map-pin": MapPin,
  medal: Medal,
  megaphone: Megaphone,
  microscope: Microscope,
  "monitor-smartphone": MonitorSmartphone,
  music: Music,
  palette: Palette,
  "pen-tool": PenTool,
  rocket: Rocket,
  school: School,
  "shield-check": ShieldCheck,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  theater: Theater,
  trophy: Trophy,
  users: Users,
  utensils: Utensils,
  volleyball: Volleyball,
};

export const ICON_NAMES = Object.keys(ICONS);

export function getIcon(name: string | null | undefined, fallback: LucideIcon = Sparkles): LucideIcon {
  return (name && ICONS[name]) || fallback;
}
